initial setup
pholleway/usda-cdl pull request #1
Opened 2022-08-02 15:53 UTC by pholleway

**Related Issue(s):**
Initial set up. 
- development requirements (pip install -r requirements-dev.txt) and pre-commit (pre-commit install).
- scripts/rename
- update setup.cfg
- update license

**PR checklist:**

- [X] Code is formatted (run `scripts/format`).
- [X] Code lints properly (run `scripts/lint`).
- [ ] Tests pass (run `scripts/test`).

2022-08-02 16:58 UTC, pholleway commented
cc @gadomski copying you so you are aware of repo. 

Also, I was hoping for some guidance in adding a the dataset "cdl" command within the stactools cli. Thanks, Pete.

2022-08-03 15:16 UTC, gadomski requested changes, later dismissed
> Also, I was hoping for some guidance in adding a the dataset "cdl" command within the stactools cli. Thanks, Pete.

The CDL command _should_ be good to go w/ the changes to `src/stactools/cdl/commands.py`...is it not working for you?

2022-08-03 15:16 UTC, gadomski commented on LICENSE
> +Copyright 2022 COMPANY Microsoft Corporation [https://www.microsoft.com/]
```suggestion
Copyright 2022 Microsoft Corporation [https://www.microsoft.com/]
```

2022-08-03 15:34 UTC, pholleway commented
> > Also, I was hoping for some guidance in adding a the dataset "cdl" command within the stactools cli. Thanks, Pete.
> 
> The CDL command _should_ be good to go w/ the changes to `src/stactools/cdl/commands.py`...is it not working for you?

Hmm... I don't think it's working. Do you mind meeting a few minutes today? It should be a quick review.

2022-08-03 15:35 UTC, pholleway commented
> > Also, I was hoping for some guidance in adding a the dataset "cdl" command within the stactools cli. Thanks, Pete.
> 
> The CDL command _should_ be good to go w/ the changes to `src/stactools/cdl/commands.py`...is it not working for you?

Thanks for taking a look, Pete. I actually have it working now.

2022-08-04 16:15 UTC, pholleway commented
@gadomski Here's my first pass at the constants.py. The tests reformat some of the classification:classes values, but not all. I'm aware of #noqa, but this doesn't seem to help. Is there a way to keep format consistent across classification:classes (rows ~54-255)? 

Also, all the color hints are the same. This is just a hold place for updating later.

2022-08-04 17:41 UTC, gadomski reviewed
We've been gravitating towards including the agency name in the stactools package name (e.g. https://github.com/pjhartzell/noaa-nclimgrid/pull/4, https://github.com/pjhartzell/noaa-nclimgrid/pull/3#issuecomment-1203942953). What do you think about renaming this `usda-cdl`?

2022-08-04 18:39 UTC, pholleway commented
> We've been gravitating towards including the agency name in the stactools package name (e.g. [pjhartzell/noaa-nclimgrid#4](https://github.com/pjhartzell/noaa-nclimgrid/pull/4), [pjhartzell/noaa-nclimgrid#3 (comment)](https://github.com/pjhartzell/noaa-nclimgrid/pull/3#issuecomment-1203942953)). What do you think about renaming this `usda-cdl`?

I really like adding the agency name. Will update!

2022-08-04 20:51 UTC, gadomski commented
> Is there a way to keep format consistent across classification:classes (rows ~54-255)?

Are you trying to keep each class either on one line or on multiple? There may be some sort of black option to encourage it to break dictionaries, but IMO it's easiest to just not worry about it -- I like to leave the formatting up to the automated tools.

2022-08-15 13:22 UTC, pholleway commented
> > Is there a way to keep format consistent across classification:classes (rows ~54-255)?
> 
> Are you trying to keep each class either on one line or on multiple? There may be some sort of black option to encourage it to break dictionaries, but IMO it's easiest to just not worry about it -- I like to leave the formatting up to the automated tools.

Thanks, Pete. I decided to not worry about it for now.

2022-08-15 13:44 UTC, merged